# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 15:50
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='avatars'),
            preserve_default=False,
        ),
    ]
