# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20180515_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Profile'),
        ),
    ]
