# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20180514_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_thumbnail',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
