# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 21:00
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20180514_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
