# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20180514_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_thumbnail',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='avatar'),
            preserve_default=False,
        ),
    ]
