# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_auto_20180514_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Post/'),
        ),
    ]
