# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_auto_20180514_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
