# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0015_remove_profile_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Post/'),
            preserve_default=False,
        ),
    ]
